// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Defaults
values: {
	image: {
		repository: "docker.io/miniflux/miniflux"
		tag:        "latest"
		digest:     ""
	}
	database: {
		url: "postgres://miniflux:secret@postgresql/miniflux?sslmode=disable"
	}
	admin: {
		password: "changeme"
	}
	ingress: {
		enabled: false
	}
}
